# Adding apt repo for php and installing php and it's necessary modules

- name: Add apt repo for php
  command: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

- name: put the deb package inside the the sources.list php
  command: echo "deb https://packages.sury.org/php/ jammy main"| sudo tee /etc/apt/sources.list.d/php.list

- name: Update repository
  apt:
    update_cache: yes

- name: Install php
  command: apt install php -y

- name: Install php modules
  apt:
    pkg:
      - php8.1-mysql
      - php8.1-common
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-curl
      - php8.1-gd
      - php8.1-imagick
      - php8.1-cli
      - php8.1-dev
      - php8.1-imap
      - php8.1-mbstring
      - php8.1-opcache
      - php8.1-soap
      - php8.1-zip
      - php8.1-intl
      - libapache2-mod-php
