# installing wget,curl, git, unzip , zip and installing the software-properties-common for ubuntu

- name: Install necessary packages
  apt:
    pkg:
      - apache2
      - git
      - wget
      - curl
      - zip
      - unzip

- name: Install software-properties-common
  command: apt -y install lsb-release apt-transport-https ca-certificates

